### ISSUE TITLE
Problem with java

### ISSUE THREAD

**Issue by grv87** [FIDATA/infrastructure#20]
In `fidata-build-toolkit` cookbook
```
    UbuntuServer16.04.2_amd64: The following packages have unmet dependencies:
    UbuntuServer16.04.2_amd64: ca-certificates-java : Depends: openjdk-7-jre-headless (>= 7~u3-2.1.1~pre1-1) but it is not going to be installed orves
    UbuntuServer16.04.2_amd64: java7-runtime-headless
    UbuntuServer16.04.2_amd64: E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**Comment by grv87** [comment]
```
    production: Some packages could not be installed. This may mean that you have
    production: requested an impossible situation or if you are using the unstable
    production: distribution that some required packages have not yet been created
    production: or been moved out of Incoming.
    production: The following information may help to resolve the situation:
    production:
    production: The following packages have unmet dependencies:
    production: openjdk-8-jre-headless : Depends: libx11-6 but it is not going to be installed
    production: Depends: libxext6 but it is not going to be installed
    production: Depends: libxi6 but it is not going to be installed
    production: Depends: libxrender1 but it is not going to be installed
    production: Depends: libxtst6 but it is not going to be installed
```
